#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

$application = new \Symfony\Component\Console\Application();

$application->add(new \App\Command\HerokuDotenvPushCommand());
$application->add(new \App\Command\HerokuDotenvPullCommand());

$application->run();
